// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package stmts

import (
	"database/sql"
)

type Food struct {
	ID        int64
	Name      string
	Calories  int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Meal struct {
	ID        int64
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type MealFoodMapping struct {
	MealID int64
	FoodID int64
}
