// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package stmts

import (
	"context"
)

const createFood = `-- name: CreateFood :one
INSERT INTO foods (name, calories) VALUES (?, ?)
RETURNING id, name, calories, created_at, updated_at
`

type CreateFoodParams struct {
	Name     string
	Calories int64
}

func (q *Queries) CreateFood(ctx context.Context, arg CreateFoodParams) (Food, error) {
	row := q.db.QueryRowContext(ctx, createFood, arg.Name, arg.Calories)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Calories,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMeal = `-- name: CreateMeal :one
INSERT INTO meals (name) VALUES (?)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateMeal(ctx context.Context, name string) (Meal, error) {
	row := q.db.QueryRowContext(ctx, createMeal, name)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMealFoodMapping = `-- name: CreateMealFoodMapping :one
INSERT INTO meal_food_mappings (meal_id, food_id) VALUES (?, ?)
RETURNING meal_id, food_id
`

type CreateMealFoodMappingParams struct {
	MealID int64
	FoodID int64
}

func (q *Queries) CreateMealFoodMapping(ctx context.Context, arg CreateMealFoodMappingParams) (MealFoodMapping, error) {
	row := q.db.QueryRowContext(ctx, createMealFoodMapping, arg.MealID, arg.FoodID)
	var i MealFoodMapping
	err := row.Scan(&i.MealID, &i.FoodID)
	return i, err
}

const getAllFoodsAndMeals = `-- name: GetAllFoodsAndMeals :many
SELECT m.name as meal_name, f.name as food_name, f.calories
FROM meals m
JOIN meal_food_mappings mf ON m.id = mf.meal_id
JOIN foods f ON mf.food_id = f.id
`

type GetAllFoodsAndMealsRow struct {
	MealName string
	FoodName string
	Calories int64
}

func (q *Queries) GetAllFoodsAndMeals(ctx context.Context) ([]GetAllFoodsAndMealsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllFoodsAndMeals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFoodsAndMealsRow
	for rows.Next() {
		var i GetAllFoodsAndMealsRow
		if err := rows.Scan(&i.MealName, &i.FoodName, &i.Calories); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFoodsAndMealsByDate = `-- name: GetAllFoodsAndMealsByDate :many
SELECT m.name as meal_name, f.name as food_name, f.calories
FROM meals m
JOIN meal_food_mappings mf ON m.id = mf.meal_id
JOIN foods f ON mf.food_id = f.id
WHERE DATE(m.created_at) = DATE(?)
`

type GetAllFoodsAndMealsByDateRow struct {
	MealName string
	FoodName string
	Calories int64
}

func (q *Queries) GetAllFoodsAndMealsByDate(ctx context.Context, date interface{}) ([]GetAllFoodsAndMealsByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllFoodsAndMealsByDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFoodsAndMealsByDateRow
	for rows.Next() {
		var i GetAllFoodsAndMealsByDateRow
		if err := rows.Scan(&i.MealName, &i.FoodName, &i.Calories); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFoodById = `-- name: GetFoodById :one
SELECT id, name, calories, created_at, updated_at FROM foods WHERE id = ?
`

func (q *Queries) GetFoodById(ctx context.Context, id int64) (Food, error) {
	row := q.db.QueryRowContext(ctx, getFoodById, id)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Calories,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFoods = `-- name: GetFoods :many
SELECT id, name, calories, created_at, updated_at FROM foods
`

func (q *Queries) GetFoods(ctx context.Context) ([]Food, error) {
	rows, err := q.db.QueryContext(ctx, getFoods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Food
	for rows.Next() {
		var i Food
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Calories,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMealById = `-- name: GetMealById :one
SELECT id, name, created_at, updated_at FROM meals WHERE id = ?
`

func (q *Queries) GetMealById(ctx context.Context, id int64) (Meal, error) {
	row := q.db.QueryRowContext(ctx, getMealById, id)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMeals = `-- name: GetMeals :many
SELECT id, name, created_at, updated_at FROM meals
`

func (q *Queries) GetMeals(ctx context.Context) ([]Meal, error) {
	rows, err := q.db.QueryContext(ctx, getMeals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFood = `-- name: UpdateFood :one
UPDATE foods 
SET name = ?, calories = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, calories, created_at, updated_at
`

type UpdateFoodParams struct {
	Name     string
	Calories int64
	ID       int64
}

func (q *Queries) UpdateFood(ctx context.Context, arg UpdateFoodParams) (Food, error) {
	row := q.db.QueryRowContext(ctx, updateFood, arg.Name, arg.Calories, arg.ID)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Calories,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
